### ISSUE TITLE
Fuzzy finder post

### ISSUE THREAD

**Issue by marcosrdac** [erfur/erfur.github.io#2]
Hey, Erfur, I hope you are alright. I read your blog post about using fzf for lauching programs from a terminal this morning. Thanks for the post. I made a very similar setup below (`menu-run`):

```sh
#!/usr/bin/env bash
compgen -c | fzf | sh
```

It is all fine except that when I run "alacritty --class launcher -e menu-run", the alacritty window that serves as a launcher continues to be open. Did you have any similar problems, or think I should try out something? I'm testing stuff for hours now (& disown, nohup, doing everything in a script). I'm lost about why I cannot lauch programs detached from the terminal.

Glad for your attention beforehand!

**Comment by erfur** [comment]
Hi, thanks for reaching out! Yes, I did have the same exact problem (see [here](https://erfur.github.io/2021/11/20/fzf_as_dmenu.html#spawning-programs-from-a-popup-terminal)). The popup persists because the spawned application is a child process with stdio bound to the terminal in the popup. The mentioned disown, nohup and & did not work for me either.

The best solution IMO is to let another process handle the application call. I found two ways to achieve this:

- systemd-run
- i3-msg

Initially everything seemed ok with systemd-run, however I noticed that I wasn't able to spawn vscode. After some debugging I found out that systemd-run could not handle applications that fork at spawn by default, it needs an argument to be able to do that. Since that would complicate things, I looked for another way and found i3-msg.

i3-msg does a better job at launching my applications as that's already part of what i3 does. Since i3-msg is telling i3 to spawn the application, there are no child processes and the popup will close successfully. Now, if you are not using i3 then I suggest you look for something that has something similar to this functionality. Otherwise you will need a custom solution like [this one](https://github.com/oem/lnch) that was developed by the author of the post I linked.

Hopefully this helps.

**Comment by marcosrdac** [comment]
Hey, @erfur, thanks for your answer!

I ended up coding a comunication protocol between the child terminal and the initial  as a solution for this yesterday:
- `tchoice` substitutes `dmenu` using `fzy` (it could be `fzf`, too) using your `TERMINAL` environment variable;
- `tlauncher` substitutes `dmenu_run` by piping `comgen -c` into `tchoice`;
- in `bspwm` I create a rule for floating and centering any new `tchoice` window;

Here is the code

```sh
$ cat tchoice
#!/usr/bin/env sh

CLASS=`basename $0`
[ $# -gt 1 ] && CHOICENAME=${1} && shift || CHOICENAME=$CLASS
PROMPT=${1}
RUNDIR="/run/user/$UID/tchoice"
CHOICEFILE="$RUNDIR/$CHOICENAME"
[ -d "$RUNDIR" ] || mkdir "$RUNDIR"

# closing old windows
[ -z "$WAYLAND_DISPLAY" ] && DOTOOL=xdotool || DOTOOL=ydotool
oldpids=`$DOTOOL search --class "$CLASS" getwindowpid %@`
for pid in $oldpids
do
  kill $pid
done

# specific options
case `basename $TERMINAL` in
  alacritty)
    geometry='--option window.dimensions.columns=40 --option window.dimensions.lines=10'
    class="--class $CHOICENAME,$CLASS" ;;
  st)
    class="-c $CLASS -n $CHOICENAME" ;;
esac
run=${run:-'-e'}

# run terminal
$TERMINAL $class $geometry $extra $run sh -c \
  "printf '`</dev/stdin`' | fzy -p '$PROMPT' > '$CHOICEFILE'"

# print choice
printf "`<$CHOICEFILE`"
printf '' > "$CHOICEFILE"
```

```sh
$ cat tlauncher
#!/usr/bin/env bash

$(compgen -c | tchoice launcher '$ ')
```

And the result:

![image](https://user-images.githubusercontent.com/7348840/156443158-a659569d-a79f-49f3-9393-1017270e14ec.png)
